title = "Sandman Config"

[aws]
aws_access_key_id = "AWS_ACCESS_KEY_ID"
aws_default_region = "DEFAULT_REGION"
aws_secret_access_key = "AWS_SECRET_ACCESS_KEY"

[directories]
backups = [
    {directory="DIRECTORY_HERE", prefix="PREFIX_NAME", bucket="BUCKET_NAME"},
]
